### ISSUE TITLE
新規登録手順の見直し

### ISSUE THREAD

**Issue by ybasviel** [ueckoken/KM4K#10]
KM4K.pyの実行中は別のプロセスからnfcリーダを使えなかったため、暫定的にRegister.shとUnregister.shを作って、いちいちサービスを止めることにした記憶があるんですが、これなんとかなりませんか？

**Comment by csenet** [comment]
@ybasviel これに関してですがKagiModのシステム周りを現在開発中の工研統合認証と連携させて以下の手順で登録するのはどうでしょうか?
(ハードウェア的にはFelicaリーダの追加が必要ですがこの前のジャンク袋を使えばなんとかなるかも)
1. IC登録ページに統合認証にログインする
2. PCにFelicaのリーダーを接続する
3. Felicaのカードをタッチする
4. 登録完了
また、Felicaの情報を可能なら他のサービス(体温の認証など)でも使えると嬉しいなぁと思っているので別途Felica情報を管理するServerを用意して、KagiModではタッチされた時にAPIを叩いて解錠して良いかをチェックするみたいな方式にしてあげると良さそうです。
システム構成
・KagiMod(Raspbeery pi)
・Felica ID Manager(kke)
Felica ID Managerに関しては私が開発しようと思います。(統合認証基盤はほぼ完成してるのでそこまで面倒くはないはず)

**Comment by csenet** [comment]
統合認証によって解決したのでClose
